version: '2.1'
services:
  postgres:
    restart: always
    build: ./postgres/
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["python", "app.py"]
