#!/bin/bash

echo "running warmup"

DIVIDER="******************************"

FILES=" ../javascript/javascript_class/person.js ../python/python_class/person.py ../ruby/ruby_class/person.rb"

for f in $FILES
do
STR_FILE="$(ls $f)"
echo "${STR_FILE}"
echo "${DIVIDER}"
echo ""
less $f
done
